# Generated by Django 3.0.3 on 2021-01-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '公司岗位', 'verbose_name_plural': '公司岗位'},
        ),
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
    ]
