# Generated by Django 3.0.3 on 2021-01-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': '应聘者简历', 'verbose_name_plural': '应聘者简历'},
        ),
        migrations.AddField(
            model_name='resume',
            name='attachment',
            field=models.FileField(blank=True, upload_to='file/', verbose_name='简历附件'),
        ),
        migrations.AddField(
            model_name='resume',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='个人照片'),
        ),
    ]
