# Generated by Django 3.0.3 on 2021-03-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20210125_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': [('export', 'Can export candidate list'), ('notify1', 'notify1 interviewer for candidate review'), ('notify2', 'notify2 interviewer for candidate review')], 'verbose_name': '候选人', 'verbose_name_plural': '候选人'},
        ),
    ]
